import { createLocalStorageStoreNg } from '@/lib/createLocalStorageStoreNg';
import { useCallback } from 'react';

const mapping = {
  "Urban / City": [
    "City",
    "Metropolitan area",
    "Metropolis",
    "Urban area",
    "Town",
    "Neighbourhood",
    "Residential area",
    "Suburb",
    "Human settlement",
    "Building",
    "High-rise building",
    "Skyscraper",
    "Condominium",
    "Apartment",
    "Home",
    "Balcony",
    "Street",
    "Sidewalk",
    "Alley",
    "Town square",
    "Public space",
    "Street light",
    "Thoroughfare",
    "Road",
    "Lane",
    "Plaza",
    "Wall",
    "Concrete",
    "Brick",
    "Stone wall",
    "Roof",
    "Floor",
    "Ceiling",
    "Room",
    "Interior design",
    "Mixed-use",
    "Cityscape",
    "Skyline"
  ],
  "People & Social": [
    "People",
    "Crowd",
    "Audience",
    "Pedestrian",
    "Customer",
    "Family car",
    "Public event",
    "Event",
    "Holiday",
    "Vacation",
    "Travel",
    "Leisure",
    "Recreation",
    "Adventure",
    "Fun",
    "Party",
    "Friendship",
    "Happiness",
    "Shopkeeper"
  ],
  "Food & Cuisine": [
    "Food",
    "Ingredient",
    "Recipe",
    "Restaurant",
    "Natural foods",
    "Produce",
    "Vegetable",
    "Leaf vegetable",
    "Fruit",
    "Meat",
    "Fish",
    "Chicken",
    "Beef",
    "Food group",
    "Staple food",
    "Breakfast",
    "Full breakfast",
    "Brunch",
    "Lunch",
    "Dinner",
    "Supper",
    "Dessert",
    "Comfort food",
    "Fast food",
    "Finger food",
    "Side dish",
    "Delicacy",
    "Bread",
    "Small bread",
    "Pastry",
    "Pizza",
    "Pizza cheese",
    "California-style pizza",
    "Flatbread",
    "Italian cuisine",
    "American cuisine",
    "Karaage",
    "Fried chicken",
    "Crispy fried chicken",
    "French fries",
    "Potato",
    "Root Vegetables",
    "Spreewald gherkins",
    "Pickled cucumber",
    "Vegetarian cuisine",
    "Soup",
    "Stew",
    "Broth",
    "Stock",
    "Ciorbă",
    "Longaniza",
    "Boudin",
    "Sausage",
    "Italian sausage",
    "Breakfast sausage",
    "Kielbasa",
    "Kishka",
    "Boerewors",
    "Olive",
    "Olives",
    "Cheese",
    "Provolone",
    "Garnish",
    "Cutlery"
  ],
  "Dining & Tableware": [
    "Tableware",
    "Dishware",
    "Plate",
    "Serveware",
    "Drinkware",
    "Barware",
    "Glass",
    "Beer glassware",
    "Cup",
    "Coffee cup",
    "Teacup",
    "Saucer",
    "Mug",
    "Platter",
    "Porcelain",
    "Bowl",
    "Spoon",
    "Stemware",
    "Table",
    "Kitchen utensil"
  ],
  "Alcohol & Beverages": [
    "Alcoholic drink",
    "Alcohol",
    "Liquor",
    "Beer",
    "Ale",
    "Lager",
    "Wheat beer",
    "Ice beer",
    "Bia hơi",
    "Paulaner Hefeweizen",
    "Imperial pint",
    "Pint glass",
    "Coffee",
    "Tea",
    "Soft drink",
    "Juice",
    "Cocktail",
    "Classic cocktail",
    "Wine cocktail",
    "Sangria",
    "Punch",
    "Tinto de verano",
    "Non-alcoholic drink",
    "Fruit syrup"
  ],
  "Water & Coast": [
    "Water",
    "Body of water",
    "Sea",
    "Ocean",
    "Coast",
    "Shore",
    "Beach",
    "Bay",
    "Cove",
    "Cape",
    "Headland",
    "Promontory",
    "Bight",
    "Raised beach",
    "Watercourse",
    "River",
    "Lake",
    "Reservoir",
    "Stream",
    "Canal",
    "Waterway",
    "Channel",
    "Mountain river",
    "Wave",
    "Wind wave",
    "Riparian zone",
    "Water resources"
  ],
  "Geology & Terrain": [
    "Terrain",
    "Geology",
    "Geological formation",
    "geological phenomenon",
    "Rock",
    "Bedrock",
    "Outcrop",
    "Cliff",
    "Klippe",
    "Fault",
    "Escarpment",
    "Mountain",
    "Mountain range",
    "Mountainous landforms",
    "Hill",
    "Hill station",
    "Highland",
    "Valley",
    "Ridge",
    "Plateau",
    "Fell",
    "Batholith",
    "Massif",
    "Soil",
    "Lacustrine plain"
  ],
  "Nature & Outdoors": [
    "Natural environment",
    "Nature",
    "Natural landscape",
    "Wilderness",
    "Forest",
    "Jungle",
    "Woodland",
    "Old-growth forest",
    "Rainforest",
    "Grove",
    "Tree",
    "Plants",
    "Plant community",
    "Vegetation",
    "Meadow",
    "Grassland",
    "Prairie",
    "Steppe",
    "Field",
    "Shrubland",
    "Chaparral",
    "Wetland",
    "Bayou",
    "Nature reserve",
    "Park",
    "Botanical garden",
    "Garden",
    "Landscape",
    "Island",
    "Lake District",
    "Summer",
    "Winter",
    "Tropics",
    "Cloud",
    "Sky",
    "Sunrise",
    "Sunset",
    "Afterglow",
    "Sunlight",
    "Morning"
  ],
  "Transport & Vehicles": [
    "Transport",
    "Motor vehicle",
    "Vehicle",
    "Land vehicle",
    "Car",
    "Family car",
    "City car",
    "Compact car",
    "Subcompact car",
    "Executive car",
    "Luxury vehicle",
    "Personal luxury car",
    "Full-size car",
    "Mid-size car",
    "Sport utility vehicle",
    "Van",
    "Bus",
    "Public transport",
    "Tour bus service",
    "Commercial vehicle",
    "Rolling stock",
    "Train",
    "Locomotive",
    "Rail transport",
    "Cable car",
    "Bicycle",
    "Mountain bike",
    "Off-road vehicle",
    "Off-roading"
  ],
  "Vehicle Parts": [
    "Wheel",
    "Tire",
    "Automotive Tire",
    "Automotive Wheel System",
    "Automotive Mirror",
    "Automotive Side-View Mirror",
    "Automotive Exterior",
    "Automotive Parking Light",
    "Automotive Tail & Brake Light",
    "Automotive lighting",
    "Vehicle registration plate",
    "Car door",
    "Hood",
    "Fender",
    "Bumper",
    "Windshield",
    "Hubcap",
    "Hardtop",
    "Tread",
    "Headlamp",
    "Lada Niva"
  ],
  "Boats & Maritime": [
    "Boat",
    "Watercraft",
    "Ship",
    "Motorboat",
    "Picnic boat",
    "Marina",
    "Harbor",
    "Port",
    "Dock",
    "Naval architecture",
    "Boats and boating--Equipment and supplies"
  ],
  "Infrastructure": [
    "Bridge",
    "Arch bridge",
    "Beam bridge",
    "Girder bridge",
    "Tied-arch bridge",
    "Bridge–tunnel",
    "Walkway",
    "Boardwalk",
    "Canopy walkway",
    "Handrail",
    "Fence",
    "pole",
    "Electrical cable",
    "Wire",
    "Overhead power line",
    "Electrical network",
    "Traffic light",
    "Sign",
    "Public utility"
  ],
  "Architecture & Landmarks": [
    "Landmark",
    "Tourist attraction",
    "Tower",
    "Clock tower",
    "Spire",
    "Steeple",
    "Finial",
    "Church",
    "Cathedral",
    "Mosque",
    "Chapel",
    "Place of worship",
    "Holy places",
    "Religious institute",
    "Parish",
    "Byzantine architecture",
    "Medieval architecture",
    "Gothic architecture",
    "Architecture",
    "Arcade",
    "Arch",
    "Courtyard",
    "Hacienda",
    "Column",
    "Vault"
  ],
  "Animals": [
    "Cat",
    "Felidae",
    "Felinae",
    "Domestic short-haired cat",
    "Whiskers",
    "Carnivores",
    "Fur",
    "Dog",
    "Canidae",
    "Street dog",
    "Guard dog",
    "Working animal",
    "Bird",
    "Wildlife",
    "Beak",
    "Shark",
    "Cartilaginous fishes",
    "Marine biology",
    "Fin",
    "Vertebrate"
  ],
  "People / Body / Clothing": [
    "Smile",
    "Facial expression",
    "Beard",
    "Facial hair",
    "Moustache",
    "Head",
    "Eye",
    "Nose",
    "Mouth",
    "Neck",
    "Ear",
    "Arm",
    "Hand",
    "Thumb",
    "Wrist",
    "Elbow",
    "Shoulder",
    "Torso",
    "Thorax",
    "Abdomen",
    "Navel",
    "Thigh",
    "Knee",
    "Ankle",
    "Foot",
    "Face",
    "Chin",
    "Cheek",
    "Jaw",
    "Hair",
    "Brown hair",
    "Eyewear",
    "Glasses",
    "Sunglasses",
    "Goggles",
    "Cap",
    "Baseball cap",
    "T-shirt",
    "Sleeveless shirt",
    "Dress",
    "Cocktail dress",
    "Undergarment",
    "Bra",
    "Briefs",
    "Lingerie",
    "Swimsuit",
    "Bikini",
    "Physical fitness",
    "Portrait photography"
  ],
  "Retail & Commerce": [
    "Retail",
    "Market",
    "Bazaar",
    "Flea market",
    "Convenience store",
    "Supermarket",
    "Bakery",
    "Shopping",
    "Corporate headquarters",
    "Headquarters",
    "Commercial building"
  ],
  "Science & Culture": [
    "Museum",
    "Science",
    "Anthropology",
    "Exhibition",
    "Art",
    "Visual arts",
    "Street art",
    "Graffiti",
    "Painting",
    "Illustration",
    "Graphics",
    "Modern art",
    "Animated cartoon",
    "Animation",
    "Fictional character"
  ],
  "Technology & Electronics": [
    "Technology",
    "Machine",
    "Engineering",
    "Electronic device",
    "Electronics",
    "Gadget",
    "Communication Device",
    "Display device",
    "Flat-panel display",
    "Television set",
    "Map",
    "Atlas",
    "Plan"
  ],
  "Objects & Materials": [
    "Furniture",
    "Chair",
    "Shelf",
    "Shelving",
    "Toy",
    "Bottle",
    "Glass bottle",
    "Plastic bottle",
    "Water bottle",
    "Beer bottle",
    "Label",
    "Flowerpot",
    "Bench",
    "Chandelier",
    "Lighting",
    "Light fixture",
    "Kitchen Appliance",
    "Home appliance",
    "Metal",
    "Steel",
    "Iron",
    "Wood",
    "Hardwood",
    "Plank",
    "Plastic",
    "Composite material",
    "Building material"
  ]
}

type ImageLabel = {
  description: string
  score?: number
  topicality?: number
}

type LabelsStore = {
  labels: Record<string, ImageLabel[]>
  labelsPrimary: Record<string, string[]>
}

const defaults: LabelsStore = {
  labels: {},
  labelsPrimary: {}
}

const {
  Provider: LabelsProvider,
  useStore,
  useSetStore,
  useStoreSelector: useLabelsStoreSelector
} = createLocalStorageStoreNg<LabelsStore>(defaults, 'labelsStore')

export const useLabels = () => {
  const store = useStore()
  const setState = useSetStore()

  const rebuildIndex = useCallback((labels: Record<string, ImageLabel[]>) => {
    const process = Object.entries(labels).reduce((acc, [path, labels]) => {
      const enhancedLabelsForPhoto = labels?.map(label => {
        const labelHeader = Object.entries(mapping).find(([_, subLabels]) => subLabels.some(sl => sl === label.description))?.[0]
        return { ...label, labelHeader }
      })

      const groupedByLabelHeader = enhancedLabelsForPhoto?.reduce((acc, label) => {
        const header = label.labelHeader ?? 'Uncategorized'
        if (!acc[header]) {
          acc[header] = []
        }
        acc[header].push(label)
        return acc
      }, {} as Record<string, typeof enhancedLabelsForPhoto>)

      const sortedLabelHeader = Object.entries(groupedByLabelHeader ?? {})
        .filter(([_, labels]) => _ !== 'Uncategorized')
        .sort((a, b) => b[1].length - a[1].length).map(([header]) => header)[0]

      console.log({ path, sortedLabelHeader, groupedByLabelHeader })

      if (sortedLabelHeader) {
        acc[path] = sortedLabelHeader
      }
      return acc
    }, {} as Record<string, string>)

    console.log(process, Object.entries(process).reduce((acc, [_, label]) => {
      acc[label] = [...(acc[label] ?? []), _]
      return acc
    }, {} as Record<string, string[]>))

    setState((prev) => ({
      ...prev, labelsPrimary: Object.entries(process).reduce((acc, [_, label]) => {
        acc[label] = [...(acc[label] ?? []), _]
        return acc
      }, {} as Record<string, string[]>)
    }))
  }, [setState])

  return {
    labels: store.labels,
    labelsPrimary: store.labelsPrimary,
    mapping,
    setLabelsFor: (path: string, labels: ImageLabel[]) => {
      setState((prev) => ({ ...prev, labels: { ...prev.labels, [path]: labels } }))
      rebuildIndex({ ...store.labels, [path]: labels })
    },
  }
}

export type { ImageLabel };

export { LabelsProvider, useLabelsStoreSelector };
