import { useEffect, useRef } from 'react';

import { Box } from '@mui/material';

import { useAdjustments, useAdjustmentsStoreSelector } from '@/context/adjustmentsStore';
import { runPipeline } from '@/middleware/interface/adjustments/canvasProcessing';
import { Stage } from '@/middleware/interface/adjustments/types';

export default function AdjustmentsProcess({
  pipeline,
}: {
  pipeline: (Stage | null)[];
}) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const originalRef = useRef<ImageData | null>(null);
  const lastWrittenRef = useRef<string | null>(null);

  const { setSetting } = useAdjustments();

  const processedBase64 = useAdjustmentsStoreSelector(
    (state) => state.processedBase64,
  );

  // Load a new source image whenever processedBase64 changes externally.
  useEffect(() => {
    if (!processedBase64) {
      originalRef.current = null;
      lastWrittenRef.current = null;
      return;
    }

    // This change came from our own previous render.
    // Don't reload it as the new original.
    if (processedBase64 === lastWrittenRef.current) {
      return;
    }

    const img = new Image();

    img.onload = () => {
      const canvas = canvasRef.current;

      if (!canvas) {
        return;
      }

      const ctx = canvas.getContext('2d');

      if (!ctx) {
        return;
      }

      canvas.width = img.width;
      canvas.height = img.height;

      ctx.drawImage(img, 0, 0);

      originalRef.current = ctx.getImageData(
        0,
        0,
        canvas.width,
        canvas.height,
      );
    };

    img.src = processedBase64;
  }, [processedBase64]);

  // Apply the pipeline exactly once whenever the pipeline changes.
  useEffect(() => {
    const canvas = canvasRef.current;
    const base = originalRef.current;

    if (!canvas || !base || !processedBase64) {
      return;
    }

    const ctx = canvas.getContext('2d');

    if (!ctx) {
      return;
    }

    const img = new ImageData(
      new Uint8ClampedArray(base.data),
      base.width,
      base.height,
    );

    runPipeline(img, pipeline);
    ctx.putImageData(img, 0, 0);

    const result = canvas.toDataURL('image/jpeg', 1);

    // Remember that this exact value was generated by us.
    lastWrittenRef.current = result;

    setSetting({
      processedBase64: result,
    });
  }, [pipeline, setSetting]);

  return (
    <Box
      sx={{
        width: '1px',
        height: '1px',
        overflow: 'hidden',
      }}
    >
      <canvas
        ref={canvasRef}
        style={{
          width: '100%',
          height: '100%',
        }}
      />
    </Box>
  );
}
